version: 0.1.{build}
branches:
  only:
  - master
build: off
test_script:
- ps: .\Build\Start-Build.ps1
on_success:  
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:GitToken):x-oauth-basic@github.com`n"
  - git config --global user.email "build@appveyor.com"
  - git config --global user.name "Appveyor"
  - git checkout %APPVEYOR_REPO_BRANCH%
  - git add *.psd1
  - git add *.md
  - git commit -m "[skip ci] AppVeyor Build %APPVEYOR_BUILD_VERSION%"
  - git push